const FREE_FALLING_OBJECT_ACCELERATION = 0.00125
const DRAG_FORCE_COEFFICIENT = 0.0008
const ROTATION_SLOWDOWN_ACCELERATION = 0.00001

const INITIAL_SHAPE_RADIUS = 10

const MIN_INITIAL_CONFETTI_SPEED = 0.9
const MAX_INITIAL_CONFETTI_SPEED = 1.7

const MIN_INITIAL_ROTATION_SPEED = 0.03
const MAX_INITIAL_ROTATION_SPEED = 0.10

const MIN_CONFETTI_ANGLE = 15
const MAX_CONFETTI_ANGLE = 82

const MAX_CONFETTI_POSITION_SHIFT = 150

const SHAPE_VISIBILITY_TRESHOLD = 100

export {
  FREE_FALLING_OBJECT_ACCELERATION,
  DRAG_FORCE_COEFFICIENT,
  ROTATION_SLOWDOWN_ACCELERATION,

  INITIAL_SHAPE_RADIUS,

  MIN_INITIAL_CONFETTI_SPEED,
  MAX_INITIAL_CONFETTI_SPEED,

  MIN_INITIAL_ROTATION_SPEED,
  MAX_INITIAL_ROTATION_SPEED,

  MIN_CONFETTI_ANGLE,
  MAX_CONFETTI_ANGLE,

  MAX_CONFETTI_POSITION_SHIFT,

  SHAPE_VISIBILITY_TRESHOLD,
}
